HichemBundle\Entity\Panier:
    type: entity
    table: panier
    indexes:
        idutilisateur:
            columns:
                - idutilisateur
    id:
        idpanier:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        etat:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: idutilisateur
            orphanRemoval: false
    lifecycleCallbacks: {  }
