HichemBundle\Entity\Utilisateur:
    type: entity
    table: utilisateur
    id:
        idutilisateur:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cin:
            type: integer
            nullable: false
            options:
                unsigned: false
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        motdepasse:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        adressemail:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        telephone:
            type: integer
            nullable: false
            options:
                unsigned: false
        datecreation:
            type: date
            nullable: false
        status:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nomcommerce:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        photoprofil:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nbpoint:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
