<?php

namespace SlimBundle\Repository;

/**
 * TitiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitiRepository extends \Doctrine\ORM\EntityRepository
{
}
