slim:
    resource: "@SlimBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"
