<?php

namespace HichemBundle\Repository;

use HichemBundle\Entity\Produit;

/**
 * LigneproduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneproduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function aloo($nom)
    {


        $repo=$this->getDoctrine()->getRepository(Produit::class);
        $produit=$repo->findOneBy(array('nomproduit' => $nom));
        $produitid=$produit->getIdproduit();
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.nomproduit like :nomproduit');
        $qb->setParameter('idproduit','%'.$produitid.'%');
        return $qb->getQuery()->getResult();
    }
}